//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyItIsMe.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebAppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebAppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyItIsMe.WebApp.Resources.WebAppResource", typeof(WebAppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;DevKit AI Integration:&lt;/strong&gt; This AI functionality comes built-in with CodeBlock.DevKit! Simply provide your AI model API key (OpenAI, Claude, Gemini, etc.), embed your documents, and get a fully functional AI assistant for your startup. No complex setup required!.
        /// </summary>
        public static string AI_DevKit_Integration_Alert {
            get {
                return ResourceManager.GetString("AI_DevKit_Integration_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant responses any time, with escalation to human agents.
        /// </summary>
        public static string AI_Feature_24x7_Availability_Desc {
            get {
                return ResourceManager.GetString("AI_Feature_24x7_Availability_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets smarter over time based on interactions and feedback.
        /// </summary>
        public static string AI_Feature_ContinuousLearning_Desc {
            get {
                return ResourceManager.GetString("AI_Feature_ContinuousLearning_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Document Processing.
        /// </summary>
        public static string AI_Feature_DocumentProcessing {
            get {
                return ResourceManager.GetString("AI_Feature_DocumentProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI trained on our entire knowledge base and documentation.
        /// </summary>
        public static string AI_Feature_DocumentProcessing_Desc {
            get {
                return ResourceManager.GetString("AI_Feature_DocumentProcessing_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Conversations.
        /// </summary>
        public static string AI_Feature_NaturalConversations {
            get {
                return ResourceManager.GetString("AI_Feature_NaturalConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration and customization options.
        /// </summary>
        public static string AI_Integration_Options {
            get {
                return ResourceManager.GetString("AI_Integration_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great question! I can guide you through our digital transformation services, recommend the right plan based on your needs, and explain how our platform integrates with your existing systems. Would you like to know more about any specific area?.
        /// </summary>
        public static string AI_Response {
            get {
                return ResourceManager.GetString("AI_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At &quot;It Can Be Yours&quot;, we&apos;ve integrated cutting-edge AI technology to provide instant, intelligent support. Our AI assistant has been trained on our knowledge base and can answer questions about our services, pricing, and more..
        /// </summary>
        public static string AI_Section_Description {
            get {
                return ResourceManager.GetString("AI_Section_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Our Intelligent AI Assistant.
        /// </summary>
        public static string AI_Section_Title {
            get {
                return ResourceManager.GetString("AI_Section_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service information and pricing.
        /// </summary>
        public static string AI_Service_Info {
            get {
                return ResourceManager.GetString("AI_Service_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Live Conversation.
        /// </summary>
        public static string AI_Start_Conversation {
            get {
                return ResourceManager.GetString("AI_Start_Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string AI_Status_Online {
            get {
                return ResourceManager.GetString("AI_Status_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can you help my business scale?.
        /// </summary>
        public static string AI_User_Question {
            get {
                return ResourceManager.GetString("AI_User_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Visits.
        /// </summary>
        public static string Authorized_Visits {
            get {
                return ResourceManager.GetString("Authorized_Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Plans.
        /// </summary>
        public static string Browse_Plans {
            get {
                return ResourceManager.GetString("Browse_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Page Creation.
        /// </summary>
        public static string Continue_Page_Creation {
            get {
                return ResourceManager.GetString("Continue_Page_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Page.
        /// </summary>
        public static string Create_Page {
            get {
                return ResourceManager.GetString("Create_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;What is CodeBlock.DevKit?&lt;/strong&gt; A comprehensive SaaS development framework that helps entrepreneurs launch their startups faster. documentation, and everything you need to build your own &quot;It Can Be Yours&quot; success story..
        /// </summary>
        public static string CTA_DevKit_Info {
            get {
                return ResourceManager.GetString("CTA_DevKit_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore This Demo.
        /// </summary>
        public static string CTA_ExploreDemo_Button {
            get {
                return ResourceManager.GetString("CTA_ExploreDemo_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full documentation &amp; support | Production-ready.
        /// </summary>
        public static string CTA_Features_Info {
            get {
                return ResourceManager.GetString("CTA_Features_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve explored what&apos;s possible with &quot;It Can Be Yours&quot; - a complete SaaS business built entirely with CodeBlock.DevKit. Now imagine creating &lt;strong&gt;your own startup&lt;/strong&gt; with the same powerful foundation, customized for your unique vision and goals..
        /// </summary>
        public static string CTA_Final_Description {
            get {
                return ResourceManager.GetString("CTA_Final_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Build Your Own Success Story?.
        /// </summary>
        public static string CTA_Final_Title {
            get {
                return ResourceManager.GetString("CTA_Final_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Your Own DevKit.
        /// </summary>
        public static string CTA_GetDevKit {
            get {
                return ResourceManager.GetString("CTA_GetDevKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get CodeBlock.DevKit.
        /// </summary>
        public static string CTA_GetDevKit_Button {
            get {
                return ResourceManager.GetString("CTA_GetDevKit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Our AI Assistant.
        /// </summary>
        public static string CTA_TryAI {
            get {
                return ResourceManager.GetString("CTA_TryAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page.
        /// </summary>
        public static string Edit_Page {
            get {
                return ResourceManager.GetString("Edit_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-Powered Support.
        /// </summary>
        public static string Feature_AIPoweredSupport_Title {
            get {
                return ResourceManager.GetString("Feature_AIPoweredSupport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive analytics and reporting dashboard to track your business performance, customer behavior, and growth metrics in real-time..
        /// </summary>
        public static string Feature_BusinessAnalytics_Description {
            get {
                return ResourceManager.GetString("Feature_BusinessAnalytics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Analytics.
        /// </summary>
        public static string Feature_BusinessAnalytics_Title {
            get {
                return ResourceManager.GetString("Feature_BusinessAnalytics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced customer relationship management with user dashboards, account management, and personalized experiences for your clients..
        /// </summary>
        public static string Feature_CustomerManagement_Description {
            get {
                return ResourceManager.GetString("Feature_CustomerManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Management.
        /// </summary>
        public static string Feature_CustomerManagement_Title {
            get {
                return ResourceManager.GetString("Feature_CustomerManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise-Grade Security.
        /// </summary>
        public static string Feature_EnterpriseSecurity {
            get {
                return ResourceManager.GetString("Feature_EnterpriseSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Processing.
        /// </summary>
        public static string Feature_PaymentProcessing_Title {
            get {
                return ResourceManager.GetString("Feature_PaymentProcessing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Integration.
        /// </summary>
        public static string Feature_SystemIntegration_Title {
            get {
                return ResourceManager.GetString("Feature_SystemIntegration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Creation.
        /// </summary>
        public static string Feature_WebsiteCreation_Title {
            get {
                return ResourceManager.GetString("Feature_WebsiteCreation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At &quot;It Can Be Yours&quot;, we provide everything businesses need to establish and grow their digital presence. Our comprehensive platform covers all aspects of modern business operations..
        /// </summary>
        public static string Features_Section_Description {
            get {
                return ResourceManager.GetString("Features_Section_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Get_Started_With_Subscription {
            get {
                return ResourceManager.GetString("Get_Started_With_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a sample startup built with &lt;strong&gt;CodeBlock.DevKit&lt;/strong&gt;. Everything you see here comes from built-in modules - no coding required. Simply customize the design, content, and features to match your vision, then launch your own startup..
        /// </summary>
        public static string Hero_Subtitle {
            get {
                return ResourceManager.GetString("Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It Can Be Yours!.
        /// </summary>
        public static string Hero_Tagline {
            get {
                return ResourceManager.GetString("Hero_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Your SaaS Idea Into Reality.
        /// </summary>
        public static string Hero_Title {
            get {
                return ResourceManager.GetString("Hero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Nav_Blog {
            get {
                return ResourceManager.GetString("Nav_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Nav_Contact {
            get {
                return ResourceManager.GetString("Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Nav_GetStarted {
            get {
                return ResourceManager.GetString("Nav_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Nav_Pricing {
            get {
                return ResourceManager.GetString("Nav_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Nav_Services {
            get {
                return ResourceManager.GetString("Nav_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Stories.
        /// </summary>
        public static string Nav_SuccessStories {
            get {
                return ResourceManager.GetString("Nav_SuccessStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active Subscriptions.
        /// </summary>
        public static string No_Active_Subscriptions {
            get {
                return ResourceManager.GetString("No_Active_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no page!.
        /// </summary>
        public static string No_Page_Alert {
            get {
                return ResourceManager.GetString("No_Page_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an active subscription but haven&apos;t created a page yet. Create your first fact page to get started..
        /// </summary>
        public static string No_Page_With_Subscription_Message {
            get {
                return ResourceManager.GetString("No_Page_With_Subscription_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No statistics available.
        /// </summary>
        public static string No_Statistics_Available {
            get {
                return ResourceManager.GetString("No_Statistics_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an active subscription yet. Subscribe to a plan to start creating your fact page..
        /// </summary>
        public static string No_Subscription_Message {
            get {
                return ResourceManager.GetString("No_Subscription_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string Page_Analytics {
            get {
                return ResourceManager.GetString("Page_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your page creation is incomplete. Continue where you left off to complete your fact page..
        /// </summary>
        public static string Page_Incomplete_Message {
            get {
                return ResourceManager.GetString("Page_Incomplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Overview.
        /// </summary>
        public static string Page_Overview {
            get {
                return ResourceManager.GetString("Page_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Pricing Demo:&lt;/strong&gt; These are sample pricing plans for this demo startup. With CodeBlock.DevKit, you can create any pricing structure, features, and business model that fits your startup idea..
        /// </summary>
        public static string Pricing_Demo_Alert {
            get {
                return ResourceManager.GetString("Pricing_Demo_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are sample pricing plans to demonstrate how you can structure your startup&apos;s monetization. Simply define pricing plans that fit your goals and vision - the platform makes it easy to customize any pricing model for your business..
        /// </summary>
        public static string Pricing_Section_Description {
            get {
                return ResourceManager.GetString("Pricing_Section_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Pricing Plans for Your Startup.
        /// </summary>
        public static string Pricing_Section_Title {
            get {
                return ResourceManager.GetString("Pricing_Section_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We retain your information for as long as necessary to provide our services or as required by law. If you choose to delete your account, we will remove your data from our systems within a reasonable timeframe..
        /// </summary>
        public static string Privacy_DataRetention_Content {
            get {
                return ResourceManager.GetString("Privacy_DataRetention_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Retention.
        /// </summary>
        public static string Privacy_DataRetention_Title {
            get {
                return ResourceManager.GetString("Privacy_DataRetention_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not share your data with third parties, except when required by law or to comply with the terms of the external login providers (e.g., Google, Microsoft, Twitter, Facebook)..
        /// </summary>
        public static string Privacy_DataSharing_Content {
            get {
                return ResourceManager.GetString("Privacy_DataSharing_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sharing.
        /// </summary>
        public static string Privacy_DataSharing_Title {
            get {
                return ResourceManager.GetString("Privacy_DataSharing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We use your information for the following purposes:&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;To authenticate your identity and log you into our platform.&lt;/li&gt;
        ///    &lt;li&gt;To manage your account and provide essential account-related communications.&lt;/li&gt;
        ///    &lt;li&gt;To send you password recovery emails if requested by you.&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;&lt;strong&gt;We do not sell, share, or use your information for marketing purposes.&lt;/strong&gt;&lt;/p&gt;.
        /// </summary>
        public static string Privacy_HowWeUseInfo_Content {
            get {
                return ResourceManager.GetString("Privacy_HowWeUseInfo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We Use Your Information.
        /// </summary>
        public static string Privacy_HowWeUseInfo_Title {
            get {
                return ResourceManager.GetString("Privacy_HowWeUseInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;When you use our platform, we may collect the following information:&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Email address: Used to create and manage your account, as well as to send password recovery emails if requested.&lt;/li&gt;
        ///    &lt;li&gt;Basic profile information: This may include your name or profile picture if provided by the external login provider.&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;We only collect information that is necessary to provide and improve our services.&lt;/p&gt;.
        /// </summary>
        public static string Privacy_InformationWeCollect_Content {
            get {
                return ResourceManager.GetString("Privacy_InformationWeCollect_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information We Collect.
        /// </summary>
        public static string Privacy_InformationWeCollect_Title {
            get {
                return ResourceManager.GetString("Privacy_InformationWeCollect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your information when you use our application and services..
        /// </summary>
        public static string Privacy_Introduction {
            get {
                return ResourceManager.GetString("Privacy_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We reserve the right to update this Privacy Policy at any time. Any changes will be posted on this page, and the Effective Date will be updated accordingly..
        /// </summary>
        public static string Privacy_PolicyChanges_Content {
            get {
                return ResourceManager.GetString("Privacy_PolicyChanges_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to Privacy Policy.
        /// </summary>
        public static string Privacy_PolicyChanges_Title {
            get {
                return ResourceManager.GetString("Privacy_PolicyChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We implement industry-standard security measures to protect your data. However, no method of transmission over the Internet or electronic storage is completely secure, and we cannot guarantee absolute security..
        /// </summary>
        public static string Privacy_SecurityMeasures_Content {
            get {
                return ResourceManager.GetString("Privacy_SecurityMeasures_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Measures.
        /// </summary>
        public static string Privacy_SecurityMeasures_Title {
            get {
                return ResourceManager.GetString("Privacy_SecurityMeasures_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You have the following rights regarding your personal information:&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Access: You can request a copy of the information we hold about you.&lt;/li&gt;
        ///    &lt;li&gt;Correction: You can request corrections to inaccurate or incomplete information.&lt;/li&gt;
        ///    &lt;li&gt;Deletion: You can request the deletion of your account and associated data.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Privacy_YourRights_Content {
            get {
                return ResourceManager.GetString("Privacy_YourRights_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Rights.
        /// </summary>
        public static string Privacy_YourRights_Title {
            get {
                return ResourceManager.GetString("Privacy_YourRights_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Page.
        /// </summary>
        public static string See_Page {
            get {
                return ResourceManager.GetString("See_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Docs.
        /// </summary>
        public static string Step_1_Button {
            get {
                return ResourceManager.GetString("Step_1_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeBlock has comprehensive documentation that covers everything you need to know about launching a startup using the DevKit..
        /// </summary>
        public static string Step_1_Description {
            get {
                return ResourceManager.GetString("Step_1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review DevKit Docs.
        /// </summary>
        public static string Step_1_Title {
            get {
                return ResourceManager.GetString("Step_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use AI agents like Cursor, ChatGPT, etc. to design your website and follow the docs to replace it with the current website..
        /// </summary>
        public static string Step_2_Description {
            get {
                return ResourceManager.GetString("Step_2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design a Website.
        /// </summary>
        public static string Step_2_Title {
            get {
                return ResourceManager.GetString("Step_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use our docs to learn the architecture and patterns for implementing high-quality business logic. Discover how simple it is to integrate your business logic with existing DevKit modules..
        /// </summary>
        public static string Step_3_Description {
            get {
                return ResourceManager.GetString("Step_3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement Your Logic.
        /// </summary>
        public static string Step_3_Title {
            get {
                return ResourceManager.GetString("Step_3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply use the Admin Panel pricing section to define your plans and discounts. Everything is ready to set up your monetization strategy effortlessly..
        /// </summary>
        public static string Step_4_Description {
            get {
                return ResourceManager.GetString("Step_4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Pricing Plans.
        /// </summary>
        public static string Step_4_Title {
            get {
                return ResourceManager.GetString("Step_4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just provide an API key from OpenAI, Google, or other AI providers, plus some business documents, and you&apos;ll have a well-designed chatbot and widget for user interaction..
        /// </summary>
        public static string Step_5_Description {
            get {
                return ResourceManager.GetString("Step_5_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create AI Chatbot.
        /// </summary>
        public static string Step_5_Title {
            get {
                return ResourceManager.GetString("Step_5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy anywhere you want. It&apos;s a cross-platform .NET application that can be deployed to Windows, Linux, and other platforms with ease..
        /// </summary>
        public static string Step_6_Description {
            get {
                return ResourceManager.GetString("Step_6_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Your Startup.
        /// </summary>
        public static string Step_6_Title {
            get {
                return ResourceManager.GetString("Step_6_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow These 6 Steps to Launch Your Startup.
        /// </summary>
        public static string Steps_Section_Title {
            get {
                return ResourceManager.GetString("Steps_Section_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First run the web apps from src/2-clients, then click on any component below to see what CodeBlock.DevKit provides.
        /// </summary>
        public static string System_Access_Subtitle {
            get {
                return ResourceManager.GetString("System_Access_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the Complete System:.
        /// </summary>
        public static string System_Access_Title {
            get {
                return ResourceManager.GetString("System_Access_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string System_AdminPanel {
            get {
                return ResourceManager.GetString("System_AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string System_AdminPanel_Status {
            get {
                return ResourceManager.GetString("System_AdminPanel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Docs.
        /// </summary>
        public static string System_API {
            get {
                return ResourceManager.GetString("System_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string System_API_Status {
            get {
                return ResourceManager.GetString("System_API_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI ChatBot.
        /// </summary>
        public static string System_ChatBot {
            get {
                return ResourceManager.GetString("System_ChatBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string System_ChatBot_Status {
            get {
                return ResourceManager.GetString("System_ChatBot_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Panel.
        /// </summary>
        public static string System_UserPanel {
            get {
                return ResourceManager.GetString("System_UserPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string System_UserPanel_Status {
            get {
                return ResourceManager.GetString("System_UserPanel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string System_Website {
            get {
                return ResourceManager.GetString("System_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string System_Website_Status {
            get {
                return ResourceManager.GetString("System_Website_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are responsible for maintaining the confidentiality of your account credentials. Please contact us immediately if you believe your account has been compromised..
        /// </summary>
        public static string Terms_AccountResponsibility_Content {
            get {
                return ResourceManager.GetString("Terms_AccountResponsibility_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Responsibilities.
        /// </summary>
        public static string Terms_AccountResponsibility_Title {
            get {
                return ResourceManager.GetString("Terms_AccountResponsibility_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using our platform, you agree to this policy..
        /// </summary>
        public static string Terms_AgreeToPolicy {
            get {
                return ResourceManager.GetString("Terms_AgreeToPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using our platform, you agree to these Terms of Service..
        /// </summary>
        public static string Terms_AgreeToTerms {
            get {
                return ResourceManager.GetString("Terms_AgreeToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Terms_ContactUs {
            get {
                return ResourceManager.GetString("Terms_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions about our policies or how we handle your data, please contact us..
        /// </summary>
        public static string Terms_ContactUsInfo {
            get {
                return ResourceManager.GetString("Terms_ContactUsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date:.
        /// </summary>
        public static string Terms_EffectiveDate {
            get {
                return ResourceManager.GetString("Terms_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;When you log in through any external provider, we may request access to your email address. This email address is used for the following purposes:&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;To create and manage your account on our platform.&lt;/li&gt;
        ///    &lt;li&gt;To use as your username for authentication purposes.&lt;/li&gt;
        ///    &lt;li&gt;To send password recovery emails, if requested by you.&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;&lt;strong&gt;We do not use your email address for marketing purposes, share it with third parties, or utilize it for any other goals.&lt;/strong&gt;&lt;/p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Terms_EmailUsage_Content {
            get {
                return ResourceManager.GetString("Terms_EmailUsage_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Your Email Address.
        /// </summary>
        public static string Terms_EmailUsage_Title {
            get {
                return ResourceManager.GetString("Terms_EmailUsage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our platform allows you to log in using third-party providers, including but not limited to Google, Microsoft, Twitter, and Facebook. By using these external login services, you agree to the respective terms and policies of the login provider you select..
        /// </summary>
        public static string Terms_ExternalLogin_Content {
            get {
                return ResourceManager.GetString("Terms_ExternalLogin_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login Providers.
        /// </summary>
        public static string Terms_ExternalLogin_Title {
            get {
                return ResourceManager.GetString("Terms_ExternalLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our platform! These Terms of Service (&quot;Terms&quot;) govern your use of our application and its associated features..
        /// </summary>
        public static string Terms_Introduction {
            get {
                return ResourceManager.GetString("Terms_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We reserve the right to modify these Terms at any time. If significant changes are made, we will notify you through our platform or via email..
        /// </summary>
        public static string Terms_Modifications_Content {
            get {
                return ResourceManager.GetString("Terms_Modifications_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications to Terms.
        /// </summary>
        public static string Terms_Modifications_Title {
            get {
                return ResourceManager.GetString("Terms_Modifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We prioritize your privacy and handle your information in compliance with our Privacy Policy. Any data obtained during the login process will only be used to facilitate your access to our platform..
        /// </summary>
        public static string Terms_PrivacyHandling_Content {
            get {
                return ResourceManager.GetString("Terms_PrivacyHandling_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and Data Handling.
        /// </summary>
        public static string Terms_PrivacyHandling_Title {
            get {
                return ResourceManager.GetString("Terms_PrivacyHandling_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using an external login provider, you agree to the terms, conditions, and privacy policies of that provider. We are not responsible for any actions taken by external login services..
        /// </summary>
        public static string Terms_ProviderResponsibility_Content {
            get {
                return ResourceManager.GetString("Terms_ProviderResponsibility_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibility of External Providers.
        /// </summary>
        public static string Terms_ProviderResponsibility_Title {
            get {
                return ResourceManager.GetString("Terms_ProviderResponsibility_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using our platform!.
        /// </summary>
        public static string Terms_ThankYou {
            get {
                return ResourceManager.GetString("Terms_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Kim.
        /// </summary>
        public static string Testimonial_3_Name {
            get {
                return ResourceManager.GetString("Testimonial_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visits.
        /// </summary>
        public static string Total_Visits {
            get {
                return ResourceManager.GetString("Total_Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Visits.
        /// </summary>
        public static string Unauthorized_Visits {
            get {
                return ResourceManager.GetString("Unauthorized_Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Visitors.
        /// </summary>
        public static string Unique_Visitors {
            get {
                return ResourceManager.GetString("Unique_Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch a Sample Startup Launch with CodeBlock DevKit.
        /// </summary>
        public static string Video_Button_Text {
            get {
                return ResourceManager.GetString("Video_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch a complete walkthrough of building a startup from scratch, then follow the same process for your own venture..
        /// </summary>
        public static string Video_Section_Description {
            get {
                return ResourceManager.GetString("Video_Section_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete end-to-end development process.
        /// </summary>
        public static string Video_Section_Subtitle {
            get {
                return ResourceManager.GetString("Video_Section_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to See How It&apos;s Done?.
        /// </summary>
        public static string Video_Section_Title {
            get {
                return ResourceManager.GetString("Video_Section_Title", resourceCulture);
            }
        }
    }
}
