//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyItIsMe.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyItIsMe.Core.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI couldn&apos;t process your reference image for some reason. Please retry or change the reference image..
        /// </summary>
        public static string AI_Image_Generation_Failed {
            get {
                return ResourceManager.GetString("AI_Image_Generation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI response failed.
        /// </summary>
        public static string AI_Response_Failed {
            get {
                return ResourceManager.GetString("AI_Response_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Content.
        /// </summary>
        public static string Contact_Content {
            get {
                return ResourceManager.GetString("Contact_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string Contact_Email {
            get {
                return ResourceManager.GetString("Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Contact_Name {
            get {
                return ResourceManager.GetString("Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact.
        /// </summary>
        public static string Fact {
            get {
                return ResourceManager.GetString("Fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Content.
        /// </summary>
        public static string Fact_Content {
            get {
                return ResourceManager.GetString("Fact_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Description.
        /// </summary>
        public static string Fact_Description {
            get {
                return ResourceManager.GetString("Fact_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Image.
        /// </summary>
        public static string Fact_ImageUrl {
            get {
                return ResourceManager.GetString("Fact_ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Title.
        /// </summary>
        public static string Fact_Title {
            get {
                return ResourceManager.GetString("Fact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts.
        /// </summary>
        public static string Facts {
            get {
                return ResourceManager.GetString("Facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Image.
        /// </summary>
        public static string Page_AvatarImage {
            get {
                return ResourceManager.GetString("Page_AvatarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Page_DisplayName {
            get {
                return ResourceManager.GetString("Page_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Information.
        /// </summary>
        public static string Page_Information {
            get {
                return ResourceManager.GetString("Page_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Image.
        /// </summary>
        public static string Page_ReferenceImage {
            get {
                return ResourceManager.GetString("Page_ReferenceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Page_Route {
            get {
                return ResourceManager.GetString("Page_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Id.
        /// </summary>
        public static string Page_SubscriptionId {
            get {
                return ResourceManager.GetString("Page_SubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string Page_UserId {
            get {
                return ResourceManager.GetString("Page_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Visits.
        /// </summary>
        public static string PageVisitType_Authorized {
            get {
                return ResourceManager.GetString("PageVisitType_Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visits.
        /// </summary>
        public static string PageVisitType_Total {
            get {
                return ResourceManager.GetString("PageVisitType_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Visits.
        /// </summary>
        public static string PageVisitType_Unauthorized {
            get {
                return ResourceManager.GetString("PageVisitType_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Visitors.
        /// </summary>
        public static string PageVisitType_UniqueVisitors {
            get {
                return ResourceManager.GetString("PageVisitType_UniqueVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Question_Content {
            get {
                return ResourceManager.GetString("Question_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Question_Description {
            get {
                return ResourceManager.GetString("Question_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Question_Order {
            get {
                return ResourceManager.GetString("Question_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required prompt was not found.
        /// </summary>
        public static string Required_Prompt_Is_Missing {
            get {
                return ResourceManager.GetString("Required_Prompt_Is_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route must only contain letters, numbers, and underscores. Special characters and spaces are not allowed..
        /// </summary>
        public static string RouteMustContainOnlyAlphanumericAndUnderscore {
            get {
                return ResourceManager.GetString("RouteMustContainOnlyAlphanumericAndUnderscore", resourceCulture);
            }
        }
    }
}
